from __future__ import annotations

import argparse
import sys
from pathlib import Path

from byteman_static.generator import GeneratorConfig, run_generator


def build_argument_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="byteman-static-generator",
        description="Scan Java sources and generate Byteman inventory/rules for runtime concurrency tracing.",
    )
    parser.add_argument(
        "--source-root",
        required=True,
        help="Java source root directory to scan recursively.",
    )
    parser.add_argument(
        "--output-dir",
        required=True,
        help="Directory where Byteman.log and generated-rules.btm will be written.",
    )
    parser.add_argument(
        "--package-prefix",
        default=None,
        help="Optional base package prefix filter (includes subpackages).",
    )
    parser.add_argument(
        "--package-regex",
        default=None,
        help="Optional package regex filter. Applied together with --package-prefix when both are set.",
    )
    parser.add_argument(
        "--helper-class",
        default="com.example.byteman.RuntimeTraceHelper",
        help="Fully qualified Java helper class used in generated Byteman actions.",
    )
    parser.add_argument(
        "--no-metadata",
        action="store_true",
        help="Disable analysis metadata JSON output.",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_argument_parser()
    args = parser.parse_args(argv)
    config = GeneratorConfig(
        source_root=Path(args.source_root).resolve(),
        output_dir=Path(args.output_dir).resolve(),
        package_prefix=args.package_prefix,
        package_regex=args.package_regex,
        helper_class=args.helper_class,
        write_metadata=not args.no_metadata,
    )

    try:
        result = run_generator(config)
    except FileNotFoundError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2
    except Exception as exc:
        print(f"ERROR: generator failed: {exc}", file=sys.stderr)
        return 1

    analysis = result.analysis
    print(f"Parser backend: {analysis.parser_backend}")
    print(f"Scanned files: {analysis.scanned_files}")
    print(f"Parsed files: {analysis.parsed_files}")
    print(f"Parse failures: {analysis.parse_failures}")
    print(f"Discovered types: {analysis.discovered_types}")
    print(f"Discovered methods: {analysis.discovered_methods}")
    print(f"Discovered fields: {analysis.discovered_fields}")
    print(f"Generated rules: {result.generated_rules}")
    print(f"Byteman.log: {result.byteman_log_path}")
    print(f"generated-rules.btm: {result.rules_path}")
    if result.metadata_path:
        print(f"analysis-metadata.json: {result.metadata_path}")

    if analysis.limitations:
        print("Limitations:")
        for limitation in analysis.limitations:
            print(f"- {limitation}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
