from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class LinuxStartupConfig:
    script_path: Path
    rules_file: Path
    runtime_log_file: Path
    java_command: str = "java"
    byteman_home_env: str = "BYTEMAN_HOME"
    byteman_agent_jar_env: str = "BYTEMAN_AGENT_JAR"
    app_jar_env: str = "APP_JAR"
    app_classpath_env: str = "APP_CLASSPATH"
    app_main_class_env: str = "APP_MAIN_CLASS"


def write_linux_startup_script(config: LinuxStartupConfig) -> Path:
    config.script_path.parent.mkdir(parents=True, exist_ok=True)
    script_contents = _build_script(config)
    config.script_path.write_text(script_contents, encoding="utf-8")
    try:
        config.script_path.chmod(0o755)
    except OSError:
        # Non-POSIX file systems may not support chmod; keep script generation successful.
        pass
    return config.script_path


def _build_script(config: LinuxStartupConfig) -> str:
    rules_file = config.rules_file.as_posix()
    runtime_log_file = config.runtime_log_file.as_posix()
    return f"""#!/usr/bin/env bash
set -euo pipefail

# Linux-only Byteman startup wrapper generated by byteman_static.
# Required env:
#   {config.byteman_home_env} : directory containing lib/byteman.jar
# One of:
#   {config.app_jar_env}      : executable application jar
#   {config.app_classpath_env} + {config.app_main_class_env} : classpath launch
#
# Optional env:
#   {config.byteman_agent_jar_env} : explicit agent jar (default: ${{{config.byteman_home_env}}}/lib/byteman.jar)
#   JAVA_OPTS                      : extra JVM options
#   BYTEMAN_VERBOSE                : true/false, default true
#
# This wrapper expects the app helper to emit structured lines, e.g.:
# BTM_EVT ts=... event=FIELD_BEFORE thread=... tid=... class=... method=... field=... write=true
# BTM_EVT ts=... event=FIELD_AFTER  thread=... tid=... class=... method=... field=... write=true

if [[ -z "${{{config.byteman_home_env}:-}}" ]]; then
  echo "Missing {config.byteman_home_env}. Set it to your Byteman installation path." >&2
  exit 2
fi

BYTEMAN_RULES_FILE="${{BYTEMAN_RULES_FILE:-{rules_file}}}"
BYTEMAN_RUNTIME_LOG="${{BYTEMAN_RUNTIME_LOG:-{runtime_log_file}}}"
BYTEMAN_AGENT_JAR="${{{config.byteman_agent_jar_env}:-${{{config.byteman_home_env}}}/lib/byteman.jar}}"
BYTEMAN_VERBOSE="${{BYTEMAN_VERBOSE:-true}}"
JAVA_CMD="${{JAVA_CMD:-{config.java_command}}}"

mkdir -p "$(dirname "$BYTEMAN_RUNTIME_LOG")"

BYTEMAN_AGENT_OPT="-javaagent:${{BYTEMAN_AGENT_JAR}}=script:${{BYTEMAN_RULES_FILE}},listener:true"
BYTEMAN_SYS_PROPS=(
  "-Dorg.jboss.byteman.verbose=${{BYTEMAN_VERBOSE}}"
  "-Dorg.jboss.byteman.transform.all=true"
  "-Dbyteman.runtime.log=${{BYTEMAN_RUNTIME_LOG}}"
)

if [[ -n "${{{config.app_jar_env}:-}}" ]]; then
  exec "$JAVA_CMD" "$BYTEMAN_AGENT_OPT" "${{BYTEMAN_SYS_PROPS[@]}}" ${{JAVA_OPTS:-}} -jar "${{{config.app_jar_env}}}" "$@"
fi

if [[ -n "${{{config.app_classpath_env}:-}}" && -n "${{{config.app_main_class_env}:-}}" ]]; then
  exec "$JAVA_CMD" "$BYTEMAN_AGENT_OPT" "${{BYTEMAN_SYS_PROPS[@]}}" ${{JAVA_OPTS:-}} -cp "${{{config.app_classpath_env}}}" "${{{config.app_main_class_env}}}" "$@"
fi

echo "Set either {config.app_jar_env} or both {config.app_classpath_env} and {config.app_main_class_env}." >&2
exit 2
"""
