from __future__ import annotations

import re
from pathlib import Path

from byteman_static.model import AnalysisResult, MethodInfo, RuleDefinition


def write_byteman_rules(result: AnalysisResult, output_path: Path, helper_class: str) -> int:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    lines, rule_count = build_rule_lines(result=result, helper_class=helper_class)
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return rule_count


def build_rule_lines(result: AnalysisResult, helper_class: str) -> tuple[list[str], int]:
    lines: list[str] = [
        "# Generated Byteman rules",
        "# Static analysis provides structural facts and suspicious access hints only.",
        "# Runtime races/deadlocks must be confirmed by helper logic and JVM state.",
        "",
    ]
    definitions = build_rule_definitions(result=result, helper_class=helper_class)

    current_class = ""
    for definition in definitions:
        if definition.class_name != current_class:
            current_class = definition.class_name
            lines.append(f"# CLASS {current_class}")
        lines.extend(_render_rule(definition))
        lines.append("")

    return lines, len(definitions)


def build_rule_definitions(result: AnalysisResult, helper_class: str) -> list[RuleDefinition]:
    definitions: list[RuleDefinition] = []
    used_rule_names: set[str] = set()

    for file_info in sorted(result.java_files, key=lambda item: item.file_path.lower()):
        for type_info in sorted(file_info.types, key=lambda item: item.qualified_name):
            for method in sorted(type_info.methods, key=lambda item: item.signature):
                entry_name = _unique_rule_name(
                    used_rule_names,
                    f"BM_ENTRY__{_sanitize(type_info.qualified_name)}__{_sanitize(method.signature)}",
                )
                exit_name = _unique_rule_name(
                    used_rule_names,
                    f"BM_EXIT__{_sanitize(type_info.qualified_name)}__{_sanitize(method.signature)}",
                )
                definitions.append(_entry_rule_definition(entry_name, type_info.qualified_name, method, helper_class))
                definitions.append(_exit_rule_definition(exit_name, type_info.qualified_name, method, helper_class))

                field_pairs = sorted(
                    {(usage.field_name, usage.access_kind) for usage in method.field_usages},
                    key=lambda item: (item[0], item[1]),
                )
                for field_name, access_kind in field_pairs:
                    before_name = _unique_rule_name(
                        used_rule_names,
                        (
                            f"BM_FIELD_BEFORE_{access_kind.upper()}__{_sanitize(type_info.qualified_name)}"
                            f"__{_sanitize(method.signature)}__{_sanitize(field_name)}"
                        ),
                    )
                    after_name = _unique_rule_name(
                        used_rule_names,
                        (
                            f"BM_FIELD_AFTER_{access_kind.upper()}__{_sanitize(type_info.qualified_name)}"
                            f"__{_sanitize(method.signature)}__{_sanitize(field_name)}"
                        ),
                    )
                    definitions.append(
                        _field_rule_definition(
                            rule_name=before_name,
                            class_name=type_info.qualified_name,
                            method=method,
                            field_name=field_name,
                            access_kind=access_kind,
                            before=True,
                            helper_class=helper_class,
                        )
                    )
                    definitions.append(
                        _field_rule_definition(
                            rule_name=after_name,
                            class_name=type_info.qualified_name,
                            method=method,
                            field_name=field_name,
                            access_kind=access_kind,
                            before=False,
                            helper_class=helper_class,
                        )
                    )
    return definitions


def _entry_rule_definition(rule_name: str, class_name: str, method: MethodInfo, helper_class: str) -> RuleDefinition:
    method_name = _quote(method.display_name)
    return RuleDefinition(
        name=rule_name,
        class_name=class_name,
        method_signature=method.signature,
        location="ENTRY",
        action=(
            f"{helper_class}.onMethodEnter(\"{_quote(class_name)}\", \"{method_name}\"); "
            f"{helper_class}.detectDeadlockNow()"
        ),
    )


def _exit_rule_definition(rule_name: str, class_name: str, method: MethodInfo, helper_class: str) -> RuleDefinition:
    method_name = _quote(method.display_name)
    return RuleDefinition(
        name=rule_name,
        class_name=class_name,
        method_signature=method.signature,
        location="EXIT",
        action=f"{helper_class}.onMethodExit(\"{_quote(class_name)}\", \"{method_name}\")",
    )


def _field_rule_definition(
    rule_name: str,
    class_name: str,
    method: MethodInfo,
    field_name: str,
    access_kind: str,
    before: bool,
    helper_class: str,
) -> RuleDefinition:
    is_write = "true" if access_kind == "write" else "false"
    action = (
        f"{helper_class}.beforeFieldAccess(\"{_quote(class_name)}\", \"{_quote(method.display_name)}\", "
        f"\"{_quote(field_name)}\", {is_write})"
        if before
        else f"{helper_class}.afterFieldAccess(\"{_quote(class_name)}\", \"{_quote(field_name)}\", {is_write})"
    )
    return RuleDefinition(
        name=rule_name,
        class_name=class_name,
        method_signature=method.signature,
        location="WRITE" if access_kind == "write" else "READ",
        action=action,
        field_name=field_name,
    )


def _render_rule(rule: RuleDefinition) -> list[str]:
    if rule.field_name:
        before_token = "AT" if "BEFORE" in rule.name else "AFTER"
        location = "WRITE" if "WRITE" in rule.name else "READ"
        location_line = f"{before_token} {location} {rule.field_name}"
    else:
        location_line = f"AT {rule.location}"
    return [
        f"RULE {rule.name}",
        f"CLASS {rule.class_name}",
        f"METHOD {rule.method_signature}",
        location_line,
        "IF TRUE",
        f"DO {rule.action}",
        "ENDRULE",
    ]


def _sanitize(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9_]", "_", value)


def _quote(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def _unique_rule_name(existing: set[str], proposed: str) -> str:
    if proposed not in existing:
        existing.add(proposed)
        return proposed
    suffix = 2
    while f"{proposed}__{suffix}" in existing:
        suffix += 1
    unique = f"{proposed}__{suffix}"
    existing.add(unique)
    return unique
