from __future__ import annotations

import re
from pathlib import Path

from byteman_static.model import AnalysisResult, MethodInfo, TypeInfo


def write_byteman_rules(result: AnalysisResult, output_path: Path, helper_class: str) -> int:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    lines, rule_count = build_rule_lines(result=result, helper_class=helper_class)
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return rule_count


def build_rule_lines(result: AnalysisResult, helper_class: str) -> tuple[list[str], int]:
    lines: list[str] = [
        "# Generated Byteman rules",
        "# Static analysis provides structural facts and suspicious access hints only.",
        "# Runtime races/deadlocks must be confirmed by helper logic and JVM state.",
        "",
    ]
    rule_count = 0
    used_rule_names: set[str] = set()

    for file_info in sorted(result.java_files, key=lambda item: item.file_path.lower()):
        for type_info in sorted(file_info.types, key=lambda item: item.qualified_name):
            lines.append(f"# CLASS {type_info.qualified_name}")
            for method in sorted(type_info.methods, key=lambda item: item.signature):
                entry_name = _unique_rule_name(
                    used_rule_names,
                    f"BM_ENTRY__{_sanitize(type_info.qualified_name)}__{_sanitize(method.signature)}",
                )
                exit_name = _unique_rule_name(
                    used_rule_names,
                    f"BM_EXIT__{_sanitize(type_info.qualified_name)}__{_sanitize(method.signature)}",
                )
                lines.extend(
                    _entry_rule(
                        rule_name=entry_name,
                        class_name=type_info.qualified_name,
                        method=method,
                        helper_class=helper_class,
                    )
                )
                lines.append("")
                lines.extend(
                    _exit_rule(
                        rule_name=exit_name,
                        class_name=type_info.qualified_name,
                        method=method,
                        helper_class=helper_class,
                    )
                )
                lines.append("")
                rule_count += 2

                field_pairs = sorted(
                    {(usage.field_name, usage.access_kind) for usage in method.field_usages},
                    key=lambda item: (item[0], item[1]),
                )
                for field_name, access_kind in field_pairs:
                    before_name = _unique_rule_name(
                        used_rule_names,
                        (
                            f"BM_FIELD_BEFORE_{access_kind.upper()}__{_sanitize(type_info.qualified_name)}"
                            f"__{_sanitize(method.signature)}__{_sanitize(field_name)}"
                        ),
                    )
                    after_name = _unique_rule_name(
                        used_rule_names,
                        (
                            f"BM_FIELD_AFTER_{access_kind.upper()}__{_sanitize(type_info.qualified_name)}"
                            f"__{_sanitize(method.signature)}__{_sanitize(field_name)}"
                        ),
                    )
                    lines.extend(
                        _field_rule(
                            rule_name=before_name,
                            class_name=type_info.qualified_name,
                            method=method,
                            field_name=field_name,
                            access_kind=access_kind,
                            before=True,
                            helper_class=helper_class,
                        )
                    )
                    lines.append("")
                    lines.extend(
                        _field_rule(
                            rule_name=after_name,
                            class_name=type_info.qualified_name,
                            method=method,
                            field_name=field_name,
                            access_kind=access_kind,
                            before=False,
                            helper_class=helper_class,
                        )
                    )
                    lines.append("")
                    rule_count += 2

    return lines, rule_count


def _entry_rule(rule_name: str, class_name: str, method: MethodInfo, helper_class: str) -> list[str]:
    method_name = _quote(method.display_name)
    return [
        f"RULE {rule_name}",
        f"CLASS {class_name}",
        f"METHOD {method.signature}",
        "AT ENTRY",
        "IF TRUE",
        (
            f"DO {helper_class}.onMethodEnter(\"{_quote(class_name)}\", \"{method_name}\"); "
            f"{helper_class}.detectDeadlockNow()"
        ),
        "ENDRULE",
    ]


def _exit_rule(rule_name: str, class_name: str, method: MethodInfo, helper_class: str) -> list[str]:
    method_name = _quote(method.display_name)
    return [
        f"RULE {rule_name}",
        f"CLASS {class_name}",
        f"METHOD {method.signature}",
        "AT EXIT",
        "IF TRUE",
        f"DO {helper_class}.onMethodExit(\"{_quote(class_name)}\", \"{method_name}\")",
        "ENDRULE",
    ]


def _field_rule(
    rule_name: str,
    class_name: str,
    method: MethodInfo,
    field_name: str,
    access_kind: str,
    before: bool,
    helper_class: str,
) -> list[str]:
    before_token = "AT" if before else "AFTER"
    access_token = "WRITE" if access_kind == "write" else "READ"
    is_write = "true" if access_kind == "write" else "false"
    action = (
        f"{helper_class}.beforeFieldAccess(\"{_quote(class_name)}\", \"{_quote(method.display_name)}\", "
        f"\"{_quote(field_name)}\", {is_write})"
        if before
        else f"{helper_class}.afterFieldAccess(\"{_quote(class_name)}\", \"{_quote(field_name)}\", {is_write})"
    )
    return [
        f"RULE {rule_name}",
        f"CLASS {class_name}",
        f"METHOD {method.signature}",
        f"{before_token} {access_token} {field_name}",
        "IF TRUE",
        f"DO {action}",
        "ENDRULE",
    ]


def _sanitize(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9_]", "_", value)


def _quote(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def _unique_rule_name(existing: set[str], proposed: str) -> str:
    if proposed not in existing:
        existing.add(proposed)
        return proposed
    suffix = 2
    while f"{proposed}__{suffix}" in existing:
        suffix += 1
    unique = f"{proposed}__{suffix}"
    existing.add(unique)
    return unique
